"""AI Business Insights (roadmap Phase 5): tell the clinic owner what's happening.

Metrics are computed deterministically from the database (so they're exact, fast, and
fully testable). A short narrative — "what's happening + what to do" — is then generated by
the LLM from those metrics, with a deterministic fallback so the report always renders even
when the model is unavailable.
"""
import logging
from datetime import datetime, timedelta

from app import db
from app.config import TIMEZONE, TZ
from app.llm import LLMUnavailable, Msg, generate

log = logging.getLogger(__name__)

PERIODS = ("day", "week")


def window(period: str, now: datetime | None = None) -> tuple[datetime, datetime, str]:
    """(since, until, label) for 'day' (since midnight) or 'week' (last 7 days)."""
    now = now or datetime.now(TZ)
    if period == "week":
        return now - timedelta(days=7), now, "Last 7 days"
    midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    return midnight, now, "Today"


def compute_metrics(tenant_id: int | None, since: datetime, until: datetime,
                    tz: str = TIMEZONE) -> dict:
    msg = db.insight_message_stats(tenant_id, since, until)
    inbound = msg["inbound"] or 0
    voice = msg["voice_inbound"] or 0
    intents = db.insight_intent_counts(tenant_id, since, until)
    peaks = db.insight_peak_hours(tenant_id, since, until, tz)
    conv = db.insight_conversion(tenant_id, since, until)
    return {
        "messages": msg["messages"] or 0,
        "inbound": inbound,
        "voice_inbound": voice,
        "voice_share_pct": round(voice / inbound * 100) if inbound else 0,
        "users": msg["users"] or 0,
        "top_inquiries": [{"intent": r["intent"], "n": r["n"]} for r in intents],
        "conversion": conv,
        "peak_hours": [{"hour": r["hour"], "n": r["n"]} for r in peaks[:3]],
        "no_shows": db.no_show_count_since(since, tenant_id),
        "no_show_reasons": [{"reason": r["reason"], "n": r["n"]}
                            for r in db.no_show_reason_breakdown(since, tenant_id)],
        "lead_mix": db.lead_band_counts(tenant_id),
        "missed_opportunities": db.insight_handover_users(tenant_id, since, until),
    }


def _metrics_brief(m: dict, label: str) -> str:
    """Compact, model-friendly rendering of the numbers for the narrative prompt."""
    inq = ", ".join(f"{r['intent']}={r['n']}" for r in m["top_inquiries"]) or "none"
    peaks = ", ".join(f"{r['hour']:02d}:00({r['n']})" for r in m["peak_hours"]) or "n/a"
    lm = m["lead_mix"]
    return (
        f"Period: {label}\n"
        f"Messages: {m['messages']} ({m['inbound']} inbound, {m['voice_share_pct']}% voice)\n"
        f"Unique patients: {m['users']}\n"
        f"Top inquiry intents: {inq}\n"
        f"Bookings: {m['conversion']['users_booked']} from {m['conversion']['users_messaged']} "
        f"patients ({m['conversion']['conversion_pct']}% conversion)\n"
        f"No-shows: {m['no_shows']}\n"
        f"Leads — hot {lm['hot']}, warm {lm['warm']}, cold {lm['cold']}\n"
        f"Conversations needing staff (missed opportunities): {m['missed_opportunities']}\n"
        f"Peak contact hours: {peaks}"
    )


_NARRATIVE_SYSTEM = (
    "You are an analyst briefing a clinic owner. Given the metrics, write 3-5 short sentences: "
    "what's happening, the biggest opportunity or risk, and 1-2 concrete actions. "
    "Plain text, no markdown, no preamble. Be specific and use the numbers given.")


def _fallback_narrative(m: dict, label: str) -> str:
    conv = m["conversion"]
    parts = [
        f"{label}: {m['inbound']} inbound messages from {m['users']} patients, "
        f"{conv['users_booked']} booked ({conv['conversion_pct']}% conversion)."
    ]
    if m["top_inquiries"]:
        top = m["top_inquiries"][0]
        parts.append(f"Most common inquiry: {top['intent']} ({top['n']}).")
    if m["peak_hours"]:
        ph = m["peak_hours"][0]
        parts.append(f"Busiest hour: {ph['hour']:02d}:00 — make sure staff are responsive then.")
    if m["missed_opportunities"]:
        parts.append(f"{m['missed_opportunities']} conversation(s) needed staff follow-up — "
                     "review them so leads aren't lost.")
    if m["no_shows"]:
        parts.append(f"{m['no_shows']} no-show(s) this period; recovery messages were sent automatically.")
    return " ".join(parts)


def narrative(metrics: dict, label: str) -> tuple[str, str]:
    """(text, source) where source is 'ai' or 'heuristic'."""
    brief = _metrics_brief(metrics, label)
    try:
        res = generate(_NARRATIVE_SYSTEM, [Msg(role="user", content=brief)], [])
        text = (res.text or "").strip()
        if text:
            return text, "ai"
    except LLMUnavailable:
        pass
    except Exception:  # noqa: BLE001
        log.exception("insights narrative LLM call failed")
    return _fallback_narrative(metrics, label), "heuristic"


def report(tenant_id: int | None, period: str = "day", tz: str = TIMEZONE,
           now: datetime | None = None) -> dict:
    """Full insights report: window + deterministic metrics + narrative."""
    period = period if period in PERIODS else "day"
    since, until, label = window(period, now)
    metrics = compute_metrics(tenant_id, since, until, tz)
    text, source = narrative(metrics, label)
    return {"period": period, "label": label, "since": since, "until": until,
            "metrics": metrics, "narrative": text, "narrative_source": source}
