"""AI Business Insights (roadmap Phase 5): tell the clinic owner what's happening.

Metrics are computed deterministically from the database (so they're exact, fast, and
fully testable). A short narrative — "what's happening + what to do" — is then generated by
the LLM from those metrics, with a deterministic fallback so the report always renders even
when the model is unavailable.
"""
import asyncio
import logging
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from app import db
from app.config import (
    INSIGHTS_DIGEST_HOUR,
    INSIGHTS_WEEKLY_DOW,
    TIMEZONE,
    TZ,
)
from app.llm import LLMUnavailable, Msg, generate

log = logging.getLogger(__name__)

PERIODS = ("day", "week")


def window(period: str, now: datetime | None = None) -> tuple[datetime, datetime, str]:
    """(since, until, label) for 'day' (since midnight) or 'week' (last 7 days)."""
    now = now or datetime.now(TZ)
    if period == "week":
        return now - timedelta(days=7), now, "Last 7 days"
    midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    return midnight, now, "Today"


def compute_metrics(tenant_id: int | None, since: datetime, until: datetime,
                    tz: str = TIMEZONE) -> dict:
    msg = db.insight_message_stats(tenant_id, since, until)
    inbound = msg["inbound"] or 0
    voice = msg["voice_inbound"] or 0
    intents = db.insight_intent_counts(tenant_id, since, until)
    peaks = db.insight_peak_hours(tenant_id, since, until, tz)
    conv = db.insight_conversion(tenant_id, since, until)
    return {
        "messages": msg["messages"] or 0,
        "inbound": inbound,
        "voice_inbound": voice,
        "voice_share_pct": round(voice / inbound * 100) if inbound else 0,
        "users": msg["users"] or 0,
        "top_inquiries": [{"intent": r["intent"], "n": r["n"]} for r in intents],
        "conversion": conv,
        "peak_hours": [{"hour": r["hour"], "n": r["n"]} for r in peaks[:3]],
        "no_shows": db.no_show_count_since(since, tenant_id),
        "no_show_reasons": [{"reason": r["reason"], "n": r["n"]}
                            for r in db.no_show_reason_breakdown(since, tenant_id)],
        "lead_mix": db.lead_band_counts(tenant_id),
        "missed_opportunities": db.insight_handover_users(tenant_id, since, until),
        "top_doctors": [{"doctor": r["doctor"], "n": r["n"]}
                        for r in db.insight_top_doctors(tenant_id, since, until)],
        "sentiment": db.sentiment_counts(tenant_id),
        "reviews": db.review_stats(tenant_id),
    }


def _metrics_brief(m: dict, label: str) -> str:
    """Compact, model-friendly rendering of the numbers for the narrative prompt."""
    inq = ", ".join(f"{r['intent']}={r['n']}" for r in m["top_inquiries"]) or "none"
    peaks = ", ".join(f"{r['hour']:02d}:00({r['n']})" for r in m["peak_hours"]) or "n/a"
    docs = ", ".join(f"{r['doctor']}={r['n']}" for r in m.get("top_doctors", [])) or "n/a"
    lm = m["lead_mix"]
    neg = m.get("sentiment", {}).get("negative", 0)
    return (
        f"Period: {label}\n"
        f"Messages: {m['messages']} ({m['inbound']} inbound, {m['voice_share_pct']}% voice)\n"
        f"Unique patients: {m['users']}\n"
        f"Top inquiry intents: {inq}\n"
        f"Most-requested doctors: {docs}\n"
        f"Bookings: {m['conversion']['users_booked']} from {m['conversion']['users_messaged']} "
        f"patients ({m['conversion']['conversion_pct']}% conversion)\n"
        f"No-shows: {m['no_shows']}\n"
        f"Leads — hot {lm['hot']}, warm {lm['warm']}, cold {lm['cold']}\n"
        f"Negative-sentiment conversations (possible complaints): {neg}\n"
        f"Conversations needing staff (missed opportunities): {m['missed_opportunities']}\n"
        f"Peak contact hours: {peaks}"
    )


# Output language for the AI narrative + digest. "ar" = Arabic, anything else = English.
_NARRATIVE_SYSTEM = {
    "en": (
        "You are an analyst briefing a clinic owner. Given the metrics, write 3-5 short sentences: "
        "what's happening, the biggest opportunity or risk, and 1-2 concrete actions. "
        "Plain text, no markdown, no preamble. Be specific and use the numbers given."),
    "ar": (
        "أنت محلل تقدّم إحاطة لمالك عيادة. استنادًا إلى المقاييس، اكتب من 3 إلى 5 جُمل قصيرة "
        "بالعربية الفصحى: ما الذي يحدث، وأكبر فرصة أو خطر، وإجراء أو إجراءان محدّدان. نص عادي "
        "بدون تنسيق وبدون مقدمات. كن دقيقًا واستخدم الأرقام المُعطاة."),
}
# Period label per language (window() returns the English one; report() localizes it).
_PERIOD_LABEL = {
    "en": {"day": "Today", "week": "Last 7 days"},
    "ar": {"day": "اليوم", "week": "آخر 7 أيام"},
}


def _label(period: str, lang: str) -> str:
    return _PERIOD_LABEL.get(lang, _PERIOD_LABEL["en"]).get(period, period)


def _fallback_narrative(m: dict, label: str, lang: str = "en") -> str:
    conv = m["conversion"]
    if lang == "ar":
        parts = [
            f"{label}: {m['inbound']} رسالة واردة من {m['users']} مريضًا، مع "
            f"{conv['users_booked']} حجزًا ({conv['conversion_pct']}% نسبة تحويل)."
        ]
        if m["top_inquiries"]:
            top = m["top_inquiries"][0]
            parts.append(f"أكثر الاستفسارات شيوعًا: {top['intent']} ({top['n']}).")
        if m["peak_hours"]:
            ph = m["peak_hours"][0]
            parts.append(f"أكثر الساعات ازدحامًا: {ph['hour']:02d}:00 — تأكّد من تجاوب الموظفين حينها.")
        if m["missed_opportunities"]:
            parts.append(f"{m['missed_opportunities']} محادثة بحاجة إلى متابعة من الموظفين — "
                         "راجعها حتى لا تُفقد الفرص.")
        if m["no_shows"]:
            parts.append(f"{m['no_shows']} زيارة فائتة هذه الفترة؛ أُرسلت رسائل الاسترجاع تلقائيًا.")
        return " ".join(parts)
    parts = [
        f"{label}: {m['inbound']} inbound messages from {m['users']} patients, "
        f"{conv['users_booked']} booked ({conv['conversion_pct']}% conversion)."
    ]
    if m["top_inquiries"]:
        top = m["top_inquiries"][0]
        parts.append(f"Most common inquiry: {top['intent']} ({top['n']}).")
    if m["peak_hours"]:
        ph = m["peak_hours"][0]
        parts.append(f"Busiest hour: {ph['hour']:02d}:00 — make sure staff are responsive then.")
    if m["missed_opportunities"]:
        parts.append(f"{m['missed_opportunities']} conversation(s) needed staff follow-up — "
                     "review them so leads aren't lost.")
    if m["no_shows"]:
        parts.append(f"{m['no_shows']} no-show(s) this period; recovery messages were sent automatically.")
    return " ".join(parts)


def _ai_narrative_enabled() -> bool:
    """Whether to spend an LLM call on the insights narrative. Toggle at runtime via the
    INSIGHTS_AI_NARRATIVE setting ("false" to turn it off and stop the Claude usage)."""
    from app import settings as settings_mod
    val = (settings_mod.get("INSIGHTS_AI_NARRATIVE", "true") or "true").strip().lower()
    return val not in ("0", "false", "no", "off")


def narrative(metrics: dict, label: str, lang: str = "en") -> tuple[str, str]:
    """(text, source): source is 'ai', 'heuristic', or 'disabled'. `lang` sets the language.
    When the AI narrative is turned off, returns an empty string (the card hides) and makes
    no LLM call — so viewing Insights costs nothing."""
    if not _ai_narrative_enabled():
        return "", "disabled"
    system = _NARRATIVE_SYSTEM.get(lang, _NARRATIVE_SYSTEM["en"])
    brief = _metrics_brief(metrics, label)
    try:
        res = generate(system, [Msg(role="user", content=brief)], [])
        text = (res.text or "").strip()
        if text:
            return text, "ai"
    except LLMUnavailable:
        pass
    except Exception:  # noqa: BLE001
        log.exception("insights narrative LLM call failed")
    return _fallback_narrative(metrics, label, lang), "heuristic"


def report(tenant_id: int | None, period: str = "day", tz: str = TIMEZONE,
           now: datetime | None = None, lang: str = "en") -> dict:
    """Full insights report: window + deterministic metrics + narrative (in `lang`)."""
    period = period if period in PERIODS else "day"
    since, until, _ = window(period, now)
    label = _label(period, lang)
    metrics = compute_metrics(tenant_id, since, until, tz)
    text, source = narrative(metrics, label, lang)
    return {"period": period, "label": label, "since": since, "until": until, "lang": lang,
            "metrics": metrics, "narrative": text, "narrative_source": source}


# --- Scheduled digest delivery (Phase 5) ---

def digest_text(rep: dict, clinic_name: str, lang: str = "en") -> str:
    """A compact WhatsApp digest of a report for the clinic owner, in `lang`."""
    m = rep["metrics"]
    c = m["conversion"]
    lm = m["lead_mix"]
    narr = (rep.get("narrative") or "").strip()
    if lang == "ar":
        lines = [f"📊 {clinic_name} — رؤى {rep['label']}"]
        if narr:
            lines += ["", narr]
        lines += [
            "",
            f"• الواردة: {m['inbound']} من {m['users']} مريضًا ({m['voice_share_pct']}% صوت)",
            f"• الحجوزات: {c['users_booked']} ({c['conversion_pct']}% تحويل)",
            f"• الزيارات الفائتة: {m['no_shows']}",
            f"• العملاء — 🔥{lm['hot']} 🌤{lm['warm']} ❄️{lm['cold']}",
        ]
        if m["peak_hours"]:
            lines.append(f"• ساعة الذروة: {m['peak_hours'][0]['hour']:02d}:00")
        if m["missed_opportunities"]:
            lines.append(f"• بحاجة لمتابعة الموظفين: {m['missed_opportunities']}")
        rv = m.get("reviews") or {}
        if rv.get("avg_rating") is not None:
            lines.append(f"• متوسط التقييم: {rv['avg_rating']}★ ({rv['responded']} تقييم)")
        return "\n".join(lines)
    lines = [f"📊 {clinic_name} — {rep['label']} insights"]
    if narr:
        lines += ["", narr]
    lines += [
        "",
        f"• Inbound: {m['inbound']} from {m['users']} patients ({m['voice_share_pct']}% voice)",
        f"• Bookings: {c['users_booked']} ({c['conversion_pct']}% conversion)",
        f"• No-shows: {m['no_shows']}",
        f"• Leads — 🔥{lm['hot']} 🌤{lm['warm']} ❄️{lm['cold']}",
    ]
    if m["peak_hours"]:
        lines.append(f"• Peak hour: {m['peak_hours'][0]['hour']:02d}:00")
    if m["missed_opportunities"]:
        lines.append(f"• Needs staff follow-up: {m['missed_opportunities']}")
    rv = m.get("reviews") or {}
    if rv.get("avg_rating") is not None:
        lines.append(f"• Avg review: {rv['avg_rating']}★ ({rv['responded']} reviews)")
    return "\n".join(lines)


def _clinic_lang(tenant: dict) -> str:
    """Digest/narrative language for a clinic — Arabic when its default agent language is
    Arabic, else English."""
    dl = ((tenant.get("clinic_data") or {}).get("clinic") or {}).get("default_language") or ""
    s = str(dl).strip().lower()
    return "ar" if (s in ("ar", "arabic") or "عرب" in str(dl)) else "en"


def _digest_recipients(tenant: dict) -> list[str]:
    """Where to send a tenant's digest: the clinic's own digest recipients only (multiple
    supported, see app.notify). The platform admin number is reserved for technical alerts,
    so digests are NEVER sent there — not even for the default/platform clinic."""
    from app import notify
    return notify.clinic_numbers(tenant, "digest")


def _digest_master_enabled() -> bool:
    """Global on/off for the scheduled digest, toggleable from Settings (DB) or env."""
    from app import settings as settings_mod
    v = (settings_mod.get("INSIGHTS_DIGEST_ENABLED", "true") or "true").strip().lower()
    return v not in ("0", "false", "no", "off")


def _digest_frequency(tenant: dict) -> str:
    """Per-clinic digest cadence: 'off' (default), 'daily', 'weekly', or 'both'."""
    notif = (tenant.get("clinic_data") or {}).get("notifications") or {}
    f = str(notif.get("digest_frequency") or "off").strip().lower()
    return f if f in ("daily", "weekly", "both") else "off"


async def run_digests(now: datetime | None = None) -> int:
    """Send due insight digests to each clinic that opted in (per-clinic frequency, default
    off). Idempotent per day via db.claim_digest. Returns the number of digests sent."""
    if not _digest_master_enabled():
        return 0
    from app import notify
    now = now or datetime.now(TZ)
    tenants = await asyncio.to_thread(db.all_active_tenants)
    sent = 0
    for t in tenants:
        freq = _digest_frequency(t)
        if freq == "off":
            continue  # this clinic hasn't enabled the digest
        recipients = _digest_recipients(t)
        if not recipients:
            continue
        tzname = t.get("timezone") or TIMEZONE
        try:
            local = now.astimezone(ZoneInfo(tzname))
        except Exception:  # noqa: BLE001 — bad tz shouldn't stop the run
            local = now
        if local.hour < INSIGHTS_DIGEST_HOUR:
            continue  # before the morning send time in this clinic's zone
        creds = {"phone_number_id": t.get("wa_phone_number_id"),
                 "access_token": t.get("wa_access_token")}
        lang = _clinic_lang(t)
        for kind in ("day", "week"):
            if kind == "day" and freq not in ("daily", "both"):
                continue
            if kind == "week" and (freq not in ("weekly", "both") or local.weekday() != INSIGHTS_WEEKLY_DOW):
                continue
            # Claim BEFORE sending so a flapping send never spams recipients twice.
            if not await asyncio.to_thread(db.claim_digest, t["id"], kind, local.date()):
                continue
            rep = await asyncio.to_thread(report, t["id"], kind, tzname, now, lang)
            text = digest_text(rep, t.get("name") or "Clinic", lang)
            n = await notify.send_many(recipients, text, creds=creds, what="digest")
            sent += 1
            log.info("insights %s digest sent to %d recipient(s) (tenant %s)", kind, n, t["id"])
    return sent
